### PR TITLE
add Page Views

### PR DESCRIPTION
**Pull request by xdvrx1**
When we add this service, it will count every hit of this repo. And this will guide us more about the visitors each day and will indicate the total views. For me, this is very helpful both for us and for those will view this repo seeing this page views. If there is the website built from this repo, it can be simply added there too.

Screenshot (1653)

### CODE REVIEW

**Comment by y2kappa** [comment]
Hey, thanks for this. This is a low profile crate and, as such, daily hits stats are not very useful. I'd be more interested in a monthly rolling window if that exists.

**Comment by y2kappa** [comment]
ping @xdvrx1  

@yonip23 any thoughts on this?

**Comment by yonip23** [comment]
> ping @xdvrx1
> 
> @yonip23 any thoughts on this?

I don't see any reason why not to make it daily. Although it's a "low profile" crate as for now, let's hope it grows big ;) 

Worst case, if you don't find the daily version valuable you can change it any time.

**Comment by y2kappa** [comment]
Sounds good, let's wait for @xdvrx1 to see if there are other options, otherwise we can merge as is.

**Comment by xdvrx1** [comment]
Yup, it's the exact idea. It's almost negligible whether you are counting that monthly or daily because in the end, it's the total count that matters. My one page, for example, now reached more than 3k visits in total. And as the author of the page, it's really fulfilling seeing that others are visiting your site, isn't it? That's the purpose of this page counter.

**Pull request merged**
